language: node_js
node_js:
- node

package:
  exclude:
    - config/dev.skill.config.json
    - config/prod.skill.config.json    
    - node_modules/mocha/**

cache:
  directories:
    - node_modules

before_script: npm install -g serverless mocha lambda-local

script: 
  - cd lambda/alexa-lambo/
  - npm install
  - npm test

deploy:
  provider: script
  script: "npm run-script deploy:dev"
  on:
    branch: master