language: node_js
node_js:
- node

package:
  exclude:
    - config/dev.skill.config.json
    - config/prod.skill.config.json    
    - node_modules/mocha/**

cache:
  directories:
    - node_modules

before_script: cd lambda/alexa-lambo/

script: 
    - npm install -g serverless mocha lambda-local
    - npm test
    - sls deploy