service:
  name: alexa-skills
   
frameworkVersion: ">=1.4.0 <2.0.0"

# key: ${optional_var}, default_val
 
provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-west-1'} 
  memorySize: 128

functions:
  alexa-lambo:
    handler: index.handler
    events:
      - alexaSkill:
          appId: amzn1.ask.skill.5e0ed43b-75aa-4c05-89d2-f0cb66b3fcef # for testing purposes only