frameworkVersion: ">=1.4.0 <2.0.0"

# key: ${optional_var}, default_val
 
provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-west-1'} 
  memorySize: 128

functions:
  alexa-lambo:
    handler: index.handler
    events:
      - alexaSkill:
          appId: ${file(./utils/deployment/config.${self:provider.stage}.json):APP_ID}